export const Icons = {
    next: 'chevron-right',
    email: 'email-outline',
    secure: 'lock-outline',
    eyeOpen: 'eye-outline',
    eyeClose: 'eye-off-outline',
    user: 'account-outline',
    calendar: 'calendar-blank-outline',
    work: 'briefcase-account-outline',
    dropDown: 'chevron-down',
    back: 'chevron-left',
    close: 'close',
    refresh: 'refresh',
    transactionsOutline: 'file-table-outline',
    transactions: 'file-table',
    add: 'plus',
    wallet: 'wallet',
    walletOutline: 'wallet-outline',
    statistics: 'triangle-wave',
    financialGoalOutline: 'trophy-outline',
    financialGoal: 'trophy-variant',
    settings: 'cog-outline',
    logout: 'logout',
    filter: 'filter-outline',
    stats: {
        up: 'arrow-top-right',
        down: 'arrow-bottom-right-thin'
    },
    circle: {
        unChecked: 'checkbox-blank-circle-outline',
        checked: 'checkbox-marked-circle'
    },
    money: 'money',
    category: 'dots-grid',
    icon: 'crosshairs-question',
    tools: 'tools',
    help: 'help-circle-outline',
    info: 'information',
    notification: 'bell-ring',
    theme: 'format-paint',
    internationalisation: 'blur-radial',
    chevron: {
        left: 'chevron-left',
        right: 'chevron-right',
        doubleLeft: 'chevron-double-left',
        doubleRight: 'chevron-double-right',
        down: 'chevron-down',
        up: 'chevron-up'
    },
    database: 'database-outline'
}
